add host namespacing to kv, start node config

diff --git a/cloud-init/master.yaml b/cloud-init/master.yaml
--- a/cloud-init/master.yaml
+++ b/cloud-init/master.yaml
@@ -1,32 +1,34 @@
 #cloud-config
 write-files:
-  - path: /etc/conf.d/nfs
-    permissions: '0644'
-    content: |
-      OPTS_RPC_MOUNTD=""
-  - path: /usr/local/bin/c2f.sh
+  - path: /root/c2f.sh
     permissions: '0755'
     content: |
       #!/bin/bash
-      FILE=$1
-      CURL_ARGS="-S -X GET"
-      BASE_URL="http://10.0.0.3:8500/v1/kv"
-      OUT_DIR=$(dirname $FILE)
-      echo "out dir: $OUT_DIR"
-      [[ ! -d $OUT_DIR ]] && mkdir -p $OUT_DIR
-      curl $CURL_ARGS $BASE_URL$FILE?raw -o $FILE
-      [[ $? -eq 0 ]] && echo -e "\nsuccess" || echo -e "\nerror"
+      FILE="$1"
+      BASE_URL="http://useless.mass.goathorde.org:8500/v1/kv"
+      URL_PREFIX="/$(hostname)"
+      FS_PREFIX="/tmp"
+      OUT_DIR=$(dirname ${FS_PREFIX}${FILE})
+      [[ ! -d "$OUT_DIR" ]] && mkdir -p "$OUT_DIR"
+      URL="${BASE_URL}${URL_PREFIX}${FILE}?raw"
+      HTTP_STATUS=$(curl -s -w "%{http_code}" -o /dev/null "$URL")
+      [ "$HTTP_STATUS" == "404" ] && URL="${BASE_URL}${FILE}?raw"
+      curl -s -o "${FS_PREFIX}${FILE}" "$URL"
+      [[ $? -eq 0 ]] && echo -e "success" || echo -e "error"
 hostname: ${node_name}
 coreos:
   etcd2:
     name: ${node_name}
     initial-cluster-token: abcdefg
-    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
-    advertise-client-urls: http://${node_ip}:2379,http://${node_ip}:4001
-    listen-peer-urls: http://${node_ip}:2380,http://${node_ip}:7001
-    initial-advertise-peer-urls: http://${node_ip}:2380,http://${node_ip}:7001
+    listen-client-urls: http://0.0.0.0:2379
+    advertise-client-urls: http://${node_ip}:2379
+    listen-peer-urls: http://${node_ip}:2380
+    initial-advertise-peer-urls: http://${node_ip}:2380
     initial-cluster: ${cluster_list}
     initial-cluster-state: new
+  flannel:
+    public_ip: ${node_ip}
+    etcd_endpoints: ${etcd_endpoints}
   fleet:
     metadata: "role=master"
   units:
@@ -39,39 +41,22 @@ coreos:
         Description=distribute config files
 
         [Service]
-        ExecStartPre=/usr/local/bin/c2f.sh /etc/cloud.cfg
-        ExecStart=echo "Done!"
+        ExecStartPre=/root/c2f.sh /etc/cloud.cfg
+        ExecStartPre=/root/c2f.sh /etc/kubernetes/manifests/kube-apiserver.yaml
+        ExecStartPre=/root/c2f.sh /etc/kubernetes/manifests/kube-controller-manager.yaml
+        ExecStartPre=/root/c2f.sh /etc/kubernetes/manifests/kube-proxy.yaml
+        ExecStartPre=/root/c2f.sh /etc/kubernetes/manifests/kube-scheduler.yaml
+        ExecStartPre=/root/c2f.sh /etc/kubernetes/ssl/${node_name}.pem
+        ExecStartPre=/root/c2f.sh /etc/kubernetes/ssl/${node_name}-key.pem
+        ExecStartPre=/root/c2f.sh /etc/kubernetes/ssl/apiserver.pem
+        ExecStartPre=/root/c2f.sh /etc/kubernetes/ssl/apiserver-key.pem
+        ExecStartPre=/root/c2f.sh /etc/kubernetes/ssl/ca.pem
+        ExecStartPre=/root/c2f.sh /etc/systemd/system/kubelet.service
+        ExecStart=/usr/bin/touch /root/.done
         RemainAfterExit=yes
         Type=oneshot
     - name: etcd2.service
       command: start
-    - name: generate-serviceaccount-key.service
-      command: start
-      content: |
-        [Unit]
-        Description=Generate service-account key file
-
-        [Service]
-        ExecStartPre=-/usr/bin/mkdir -p /opt/bin
-        ExecStart=/bin/openssl genrsa -out /opt/bin/kube-serviceaccount.key 2048 2>/dev/null
-        RemainAfterExit=yes
-        Type=oneshot
-    - name: setup-network-environment.service
-      command: start
-      content: |
-        [Unit]
-        Description=Setup Network Environment
-        Documentation=https://github.com/kelseyhightower/setup-network-environment
-        Requires=network-online.target
-        After=network-online.target
-
-        [Service]
-        ExecStartPre=-/usr/bin/mkdir -p /opt/bin
-        ExecStartPre=-/usr/bin/curl -L -o /opt/bin/setup-network-environment -z /opt/bin/setup-network-environment https://github.com/kelseyhightower/setup-network-environment/releases/download/1.0.1/setup-network-environment
-        ExecStartPre=/usr/bin/chmod +x /opt/bin/setup-network-environment
-        ExecStart=/opt/bin/setup-network-environment
-        RemainAfterExit=yes
-        Type=oneshot
     - name: fleet.service
       command: start
     - name: flanneld.service
@@ -81,77 +66,19 @@ coreos:
           content: |
             [Unit]
             Requires=etcd2.service
+
             [Service]
-            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.244.0.0/16", "Backend": {"Type": "vxlan"}}'
+            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"${pod_network}", "Backend": {"Type": "vxlan"}}'
     - name: docker.service
       command: start
-    - name: kube-apiserver.service
+      drop-ins:
+        - name: 40-flannel.conf
+          content: |
+            [Unit]
+            Requires=flanneld.service
+            After=flanneld.service
+    - name: kubelet.service
       command: start
-      content: |
-        [Unit]
-        Description=Kubernetes API Server
-        Documentation=https://github.com/kubernetes/kubernetes
-        Requires=setup-network-environment.service etcd2.service generate-serviceaccount-key.service
-        After=setup-network-environment.service etcd2.service generate-serviceaccount-key.service
-
-        [Service]
-        EnvironmentFile=/etc/network-environment
-        ExecStartPre=-/usr/bin/mkdir -p /opt/bin
-        ExecStartPre=-/usr/bin/curl -L -o /opt/bin/kube-apiserver -z /opt/bin/kube-apiserver https://storage.googleapis.com/kubernetes-release/release/v1.2.2/bin/linux/amd64/kube-apiserver
-        ExecStartPre=/usr/bin/chmod +x /opt/bin/kube-apiserver
-        ExecStart=/opt/bin/kube-apiserver \
-        --service-account-key-file=/opt/bin/kube-serviceaccount.key \
-        --service-account-lookup=false \
-        --admission-control=NamespaceLifecycle,NamespaceAutoProvision,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota \
-        --runtime-config=api/v1 \
-        --allow-privileged=true \
-        --insecure-bind-address=0.0.0.0 \
-        --insecure-port=8080 \
-        --kubelet-https=true \
-        --secure-port=6443 \
-        --service-cluster-ip-range=10.100.0.0/16 \
-        --etcd-servers=http://127.0.0.1:2379 \
-        --bind-address=${node_ip} \
-        --logtostderr=true \
-        --cloud-config="/etc/cloud.cfg" \
-        --cloud-provider="openstack"
-        Restart=always
-        RestartSec=10
-    - name: kube-controller-manager.service
-      command: start
-      content: |
-        [Unit]
-        Description=Kubernetes Controller Manager
-        Documentation=https://github.com/kubernetes/kubernetes
-        Requires=kube-apiserver.service
-        After=kube-apiserver.service
-
-        [Service]
-        ExecStartPre=-/usr/bin/curl -L -o /opt/bin/kube-controller-manager -z /opt/bin/kube-controller-manager https://storage.googleapis.com/kubernetes-release/release/v1.2.2/bin/linux/amd64/kube-controller-manager
-        ExecStartPre=/usr/bin/chmod +x /opt/bin/kube-controller-manager
-        ExecStart=/opt/bin/kube-controller-manager \
-        --service-account-private-key-file=/opt/bin/kube-serviceaccount.key \
-        --master=127.0.0.1:8080 \
-        --cloud-config="/etc/cloud.cfg" \
-        --cloud-provider="openstack" \
-        --logtostderr=true
-        Restart=always
-        RestartSec=10
-    - name: kube-scheduler.service
-      command: start
-      content: |
-        [Unit]
-        Description=Kubernetes Scheduler
-        Documentation=https://github.com/kubernetes/kubernetes
-        Requires=kube-apiserver.service
-        After=kube-apiserver.service
-
-        [Service]
-        ExecStartPre=-/usr/bin/curl -L -o /opt/bin/kube-scheduler -z /opt/bin/kube-scheduler https://storage.googleapis.com/kubernetes-release/release/v1.2.2/bin/linux/amd64/kube-scheduler
-        ExecStartPre=/usr/bin/chmod +x /opt/bin/kube-scheduler
-        ExecStart=/opt/bin/kube-scheduler --master=127.0.0.1:8080
-        Restart=always
-        RestartSec=10
   update:
     group: stable
     reboot-strategy: off
diff --git a/cloud-init/node.yaml b/cloud-init/node.yaml
--- a/cloud-init/node.yaml
+++ b/cloud-init/node.yaml
@@ -5,15 +5,16 @@ write-files:
     content: |
       #!/bin/bash
       FILE="$1"
-      CURL_ARGS="-X GET"
       BASE_URL="http://useless.mass.goathorde.org:8500/v1/kv"
-      URL_PREFIX=""
-      OUT_DIR=$(dirname $FILE)
-      echo "out dir: $OUT_DIR"
-      [[ ! -d $OUT_DIR ]] && mkdir -p $OUT_DIR
-      echo "url: $BASE_URL$URL_PREFIX$FILE?raw"
-      curl $CURL_ARGS $BASE_URL$URL_PREFIX$FILE?raw -o $FILE
-      [[ $? -eq 0 ]] && echo -e "\nsuccess" || echo -e "\nerror"
+      URL_PREFIX="/$(hostname)"
+      FS_PREFIX="/tmp"
+      OUT_DIR=$(dirname ${FS_PREFIX}${FILE})
+      [[ ! -d "$OUT_DIR" ]] && mkdir -p "$OUT_DIR"
+      URL="${BASE_URL}${URL_PREFIX}${FILE}?raw"
+      HTTP_STATUS=$(curl -s -w "%{http_code}" -o /dev/null "$URL")
+      [ "$HTTP_STATUS" == "404" ] && URL="${BASE_URL}${FILE}?raw"
+      curl -s -o "${FS_PREFIX}${FILE}" "$URL"
+      [[ $? -eq 0 ]] && echo -e "success" || echo -e "error"
 hostname: ${node_name}
 coreos:
   etcd2:
@@ -33,80 +34,47 @@ coreos:
   units:
     - name: systemd-timesyncd.service
       command: start
+    - name: populate.service
+      command: start
+      content: |
+        [Unit]
+        Description=distribute config files
+
+        [Service]
+        ExecStartPre=/root/c2f.sh /etc/cloud.cfg
+        ExecStartPre=/root/c2f.sh /etc/kubernetes/manifests/kube-proxy.yaml
+        ExecStartPre=/root/c2f.sh /etc/kubernetes/ssl/${node_name}.pem
+        ExecStartPre=/root/c2f.sh /etc/kubernetes/ssl/${node_name}-key.pem
+        ExecStartPre=/root/c2f.sh /etc/kubernetes/ssl/ca.pem
+        ExecStartPre=/root/c2f.sh /etc/kubernetes/worker-kubeconfig.yaml
+        ExecStartPre=/root/c2f.sh /etc/systemd/system/kubelet.service
+        ExecStart=/usr/bin/touch /root/.done
+        RemainAfterExit=yes
+        Type=oneshot
     - name: etcd2.service
       command: start
     - name: fleet.service
       command: start
     - name: flanneld.service
       command: start
+      drop-ins:
+        - name: 50-network-config.conf
+          content: |
+            [Unit]
+            Requires=etcd2.service
+
+            [Service]
+            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"${pod_network}", "Backend": {"Type": "vxlan"}}'
     - name: docker.service
       command: start
-    - name: setup-network-environment.service
+      drop-ins:
+        - name: 40-flannel.conf
+          content: |
+            [Unit]
+            Requires=flanneld.service
+            After=flanneld.service
+    - name: kubelet.service
       command: start
-      content: |
-        [Unit]
-        Description=Setup Network Environment
-        Documentation=https://github.com/kelseyhightower/setup-network-environment
-        Requires=network-online.target
-        After=network-online.target
-
-        [Service]
-        ExecStartPre=-/usr/bin/mkdir -p /opt/bin
-        ExecStartPre=-/usr/bin/curl -L -o /opt/bin/setup-network-environment -z /opt/bin/setup-network-environment https://github.com/kelseyhightower/setup-network-environment/releases/download/1.0.1/setup-network-environment
-        ExecStartPre=/usr/bin/chmod +x /opt/bin/setup-network-environment
-        ExecStart=/opt/bin/setup-network-environment
-        RemainAfterExit=yes
-        Type=oneshot
-    - name: kube-proxy.service
-      command: start
-      content: |
-        [Unit]
-        Description=Kubernetes Proxy
-        Documentation=https://github.com/kubernetes/kubernetes
-        Requires=setup-network-environment.service
-        After=setup-network-environment.service
-
-        [Service]
-        ExecStartPre=-/usr/bin/curl -L -o /opt/bin/kube-proxy -z /opt/bin/kube-proxy https://storage.googleapis.com/kubernetes-release/release/v1.2.2/bin/linux/amd64/kube-proxy
-        ExecStartPre=/usr/bin/chmod +x /opt/bin/kube-proxy
-        # wait for kubernetes master to be up and ready
-        ExecStartPre=/opt/bin/wupiao ${master_ip} 8080
-        ExecStart=/opt/bin/kube-proxy \
-        --master=${master_ip}:8080 \
-        --logtostderr=true
-        Restart=always
-        RestartSec=10
-    - name: kube-kubelet.service
-      command: start
-      content: |
-        [Unit]
-        Description=Kubernetes Kubelet
-        Documentation=https://github.com/kubernetes/kubernetes
-        Requires=setup-network-environment.service
-        After=setup-network-environment.service
-
-        [Service]
-        EnvironmentFile=/etc/network-environment
-        ExecStartPre=-/usr/bin/curl -L -o /opt/bin/kubelet -z /opt/bin/kubelet https://storage.googleapis.com/kubernetes-release/release/v1.2.2/bin/linux/amd64/kubelet
-        ExecStartPre=/usr/bin/chmod +x /opt/bin/kubelet
-        # wait for kubernetes master to be up and ready
-        ExecStartPre=/opt/bin/wupiao ${master_ip} 8080
-        ExecStart=/opt/bin/kubelet \
-        --address=0.0.0.0 \
-        --port=10250 \
-        --hostname-override=${node_name} \
-        --api-servers=${master_ip}:8080 \
-        --allow-privileged=true \
-        --logtostderr=true \
-        --cadvisor-port=4194 \
-        --healthz-bind-address=0.0.0.0 \
-        --healthz-port=10248 \
-        --cloud-config="/etc/cloud.cfg" \
-        --cloud-provider="openstack" \
-        --cluster-dns=10.100.0.2 \
-        --cluster-domain=cluster.local
-        Restart=always
-        RestartSec=10
   update:
     group: stable
     reboot-strategy: off
